import { useNavigate } from 'react-router-dom';
import { Button } from '@/components/ui/button';
import { ArrowLeft } from 'lucide-react';

const TermsOfService = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-background text-foreground">
      <nav className="fixed top-0 left-0 right-0 z-50 bg-black/40 backdrop-blur-xl border-b border-white/10">
        <div className="max-w-4xl mx-auto flex items-center gap-3 px-4 py-3">
          <Button variant="ghost" size="sm" onClick={() => navigate(-1)} className="text-amber-400 hover:text-white">
            <ArrowLeft className="h-4 w-4 mr-1" /> Back
          </Button>
          <span className="text-lg font-bold text-white">Terms of Service</span>
        </div>
      </nav>

      <main className="max-w-4xl mx-auto px-4 pt-24 pb-16 prose prose-invert prose-amber max-w-none">
        <h1 className="text-3xl font-bold bg-gradient-to-r from-amber-400 via-yellow-500 to-amber-600 bg-clip-text text-transparent">
          Terms of Service
        </h1>
        <p className="text-muted-foreground text-sm">Last updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</p>

        <section className="space-y-4 mt-8">
          <h2 className="text-xl font-semibold text-foreground">1. Acceptance of Terms</h2>
          <p className="text-muted-foreground">
            By accessing or using ElectroDoctor ("the Service"), a product of ZTech Electronics Limited, you agree to be bound by these Terms of Service. If you do not agree, do not use the Service.
          </p>
        </section>

        <section className="space-y-4 mt-8">
          <h2 className="text-xl font-semibold text-foreground">2. Description of Service</h2>
          <p className="text-muted-foreground">
            ElectroDoctor is an AI-powered gadget diagnostic and repair assistant platform. The Service provides AI-based device diagnosis, troubleshooting guidance, battery health monitoring, repair recommendations, and related features. The Service is intended for informational purposes and does not replace professional repair services.
          </p>
        </section>

        <section className="space-y-4 mt-8">
          <h2 className="text-xl font-semibold text-foreground">3. User Accounts</h2>
          <ul className="text-muted-foreground space-y-2 list-disc pl-6">
            <li>You must provide accurate, current information when creating an account.</li>
            <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
            <li>You must be at least 16 years of age to use this Service.</li>
            <li>One person may not maintain more than one account.</li>
          </ul>
        </section>

        <section className="space-y-4 mt-8">
          <h2 className="text-xl font-semibold text-foreground">4. Acceptable Use</h2>
          <p className="text-muted-foreground">You agree not to:</p>
          <ul className="text-muted-foreground space-y-2 list-disc pl-6">
            <li>Use the Service for any unlawful purpose or in violation of any applicable laws.</li>
            <li>Upload malicious content, viruses, or harmful code.</li>
            <li>Attempt to gain unauthorized access to any part of the Service.</li>
            <li>Reverse engineer, decompile, or disassemble any part of the Service.</li>
            <li>Use automated tools (bots, scrapers) to access the Service without permission.</li>
          </ul>
        </section>

        <section className="space-y-4 mt-8">
          <h2 className="text-xl font-semibold text-foreground">5. AI-Generated Content Disclaimer</h2>
          <p className="text-muted-foreground">
            The diagnostic results, repair suggestions, and other content generated by our AI are provided "as-is" for informational purposes only. ZTech Electronics Limited does not guarantee the accuracy, completeness, or reliability of AI-generated diagnoses. Always consult a qualified technician before performing hardware repairs.
          </p>
        </section>

        <section className="space-y-4 mt-8">
          <h2 className="text-xl font-semibold text-foreground">6. Intellectual Property</h2>
          <p className="text-muted-foreground">
            All content, features, and functionality of ElectroDoctor, including but not limited to software, text, graphics, logos, and AI models, are the exclusive property of ZTech Electronics Limited and are protected by intellectual property laws.
          </p>
        </section>

        <section className="space-y-4 mt-8">
          <h2 className="text-xl font-semibold text-foreground">7. User Data & Uploaded Content</h2>
          <p className="text-muted-foreground">
            By uploading images, videos, or other content to the Service, you grant ZTech Electronics Limited a non-exclusive, royalty-free license to use this content solely for the purpose of providing and improving the Service. You retain ownership of your content.
          </p>
        </section>

        <section className="space-y-4 mt-8">
          <h2 className="text-xl font-semibold text-foreground">8. Limitation of Liability</h2>
          <p className="text-muted-foreground">
            To the maximum extent permitted by law, ZTech Electronics Limited shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the Service, including but not limited to damage to devices resulting from following AI-generated repair suggestions.
          </p>
        </section>

        <section className="space-y-4 mt-8">
          <h2 className="text-xl font-semibold text-foreground">9. Service Modifications</h2>
          <p className="text-muted-foreground">
            We reserve the right to modify, suspend, or discontinue the Service at any time without prior notice. We shall not be liable to you or any third party for any modification, suspension, or discontinuation.
          </p>
        </section>

        <section className="space-y-4 mt-8">
          <h2 className="text-xl font-semibold text-foreground">10. Termination</h2>
          <p className="text-muted-foreground">
            We may terminate or suspend your account at our sole discretion, without prior notice, for conduct that we determine violates these Terms or is harmful to other users, us, or third parties.
          </p>
        </section>

        <section className="space-y-4 mt-8">
          <h2 className="text-xl font-semibold text-foreground">11. Governing Law</h2>
          <p className="text-muted-foreground">
            These Terms shall be governed by and construed in accordance with the laws of the jurisdiction in which ZTech Electronics Limited operates, without regard to its conflict of law provisions.
          </p>
        </section>

        <section className="space-y-4 mt-8">
          <h2 className="text-xl font-semibold text-foreground">12. Contact</h2>
          <p className="text-muted-foreground">
            For questions about these Terms, contact us at{' '}
            <a href="mailto:support@ztechelectronics.com" className="text-primary hover:underline">support@ztechelectronics.com</a>
          </p>
        </section>
      </main>
    </div>
  );
};

export default TermsOfService;
