// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcjimrlyhtqbnsbujdmj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjamltcmx5aHRxYm5zYnVqZG1qIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNTU4MzQsImV4cCI6MjA2NTczMTgzNH0.86t2t1yzKOigWj-SOR5Z7-EkDPe6YwyIYoHeBv4dCBA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);